import mongoose from 'mongoose';

const productSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, 'Product name is required'],
    trim: true
  },
  description: {
    type: String,
    required: [true, 'Product description is required']
  },
  aiDescription: {
    type: String, // Generated by Gemini
    default: ''
  },
  price: {
    type: Number,
    required: [true, 'Product price is required'],
    min: [0, 'Price cannot be negative']
  },
  originalPrice: {
    type: Number,
    min: 0
  },
  images: [{
    type: String,
    required: true
  }],
  category: {
    type: String,
    required: true,
    enum: [
      'pokemon', 'pokemon-go', 'anime', 'vintage', 'holo', 
      'rare', 'starter', 'legendary', 'custom', 'bundle'
    ]
  },
  pokemonName: {
    type: String, // e.g., "Pikachu", "Charizard"
    trim: true
  },
  pokemonNumber: {
    type: Number // Pokedex number
  },
  generation: {
    type: Number, // 1-9
    min: 1,
    max: 9
  },
  // Enhanced Pokemon data
  pokemonData: {
    types: [String], // e.g., ["fire", "flying"]
    abilities: [String], // e.g., ["blaze", "solar-power"]
    baseStats: {
      hp: Number,
      attack: Number,
      defense: Number,
      specialAttack: Number,
      specialDefense: Number,
      speed: Number,
      total: Number // Sum of all stats
    },
    baseExperience: Number,
    height: Number, // in meters
    weight: Number, // in kg
    isLegendary: Boolean,
    isMythical: Boolean,
    powerLevel: {
      type: String,
      enum: ['weak', 'average', 'strong', 'very-strong', 'legendary'],
      default: 'average'
    }
  },
  rarity: {
    type: String,
    enum: ['common', 'uncommon', 'rare', 'ultra-rare', 'legendary'],
    default: 'common'
  },
  stock: {
    type: Number,
    required: true,
    min: [0, 'Stock cannot be negative'],
    default: 0
  },
  seller: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  status: {
    type: String,
    enum: ['active', 'inactive', 'out-of-stock'],
    default: 'active'
  },
  dimensions: {
    width: Number, // in cm
    height: Number // in cm
  },
  material: {
    type: String,
    default: 'vinyl'
  },
  rating: {
    average: {
      type: Number,
      default: 0,
      min: 0,
      max: 5
    },
    count: {
      type: Number,
      default: 0
    }
  },
  tags: [{
    type: String,
    trim: true
  }],
  featured: {
    type: Boolean,
    default: false
  },
  salesCount: {
    type: Number,
    default: 0
  }
}, {
  timestamps: true
});

// Indexes for better search performance
productSchema.index({ name: 'text', description: 'text', pokemonName: 'text' });
productSchema.index({ category: 1, rarity: 1 });
productSchema.index({ pokemonNumber: 1 });
productSchema.index({ seller: 1 });

export default mongoose.model('Product', productSchema);
